"""Added author field to books

Revision ID: 0623f3a8fad6
Revises: 
Create Date: 2024-07-28 01:05:32.540520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0623f3a8fad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###
